# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(name: "James Billings", email: "jamesbonline@gmail.com", gender: "Male", age: 20)
User.create(name: "Carolyne Billings", email: "carolyneonline@gmail.com", gender: "Female", age: 35)
Block.create(page: "home",  usecase: "opening_talk", content: "Carolyne specializes in playful, yet mindful all level Vinyasa Flow classes, fusing the energetic style of Prana Flow Yoga while blending a strong component of hands on alignment and awareness in addition to breath control. Carolyne believes in taking the practice seriously but your self lightly and aims to make yoga accessible to everyone, structuring her classes so that all who come to their mat can experience a mind, body connection.")
Block.create(page: "about", usecase: "about_text", content: "<p>I remember taking my first yoga class in 2002 at the Yoga Tree in San Francisco. The teacher was a very petite man with long silver hair and he was a ball of positive energy and delight. I had never seen this kind of grounded enthusiasm nor had I ever felt what it was like to be mindful of my body, my breath and my mind, all at the same time.</p><p>I fell in love with the practice of yoga and have travelled the world doing yoga, having just transitioned from London where I was involved with one of the leading UK yoga studios, Triyoga.</p><p>I would like to honor my primary teacher, Prana Flow creator, Shiva Rea, who continues to remind me to feel the pulse of life and move with power and grace. Other main influences are Keri Bergeron, Kathryn Budig, Jason Crandell and Claire Missingham. I would like to deeply thank my teacher, Seane Corn, for encouraging me everyday to “Ignore the story and see the soul. And remember to love—you will never regret it”</p><p>Having completed my 200 hr teacher training and continuing towards my 300 hr with Gina Caputo, I am eager to teach from a place of compassion, patience, humility and an occasional side of humor. I will continue to be a student first, teacher second and learn from every experience grateful enough to encounter.</p><p>I currently reside in Denver, Colorado where I love doing yoga, playing in mountain streams, and giggling with my daughter and equally entertaining husband. Thank you for visiting my site and for your interest in the practice of living yoga! Hope to see you on the mat soon!</p><div class=\"panel-quote\"><p>The thought manifests as the word</p><p>The word manifests as the deed</p><p>The deed develops into habit</p><p>And habit hardens into character</p><p>So watch the thought</p><p>And its ways with care</p><p>And let it spring from love</p><p>Born out of concern for all beings.</p><p>~The Buddha’’</p></div>")